### ISSUE TITLE
Make it clearer how to create a new db_driver

### ISSUE THREAD

**Issue by rossjrw** [facebook/pyaib#22]
https://github.com/facebook/pyaib/wiki/db

> Just decorate your db driver class, and implement all the methods mentioned in the doc at the top of pyaib.db from pyaib.db import db_driver

It's not quite as easy as that.

1. The location of the new db_driver must be specified in the config file under `db.backend`.

2. The location of the file must contain a `.`, otherwise pyaib will search its internal `dbd` directory (which only contains one potential database driver anyway). This also restricts the possible locations of the file - it can't be in the top-level directory, for example.

3. The location of the database file itself must be specified for each new db_driver, and this is especially confusing without carefully tracking the odd decisions in `db.py` - it must be specified as "`db.driver.{}`", where {} is the last part of the value of `db.backend` - for example, if `db.backend` is `plugins.database_manager`, then the location of the database file must be stored in `db.driver.database_manager`. What if the user picks the name "sqlite" as their filename - why destroy the name data and introduce ambiguity?

I'd like to request that the documentation for this be cleaned up, so that others don't have to track through the source code to make pyaib recognise their own database driver.

**Comment by fried** [comment]
Hey sorry this took so long, this projects while still used in fb, just doesn't see a lot of effort since its in stable maintenance mode. 

I have updated the wiki with you suggestions.   The assumptions I made way back when this was written may have been a little naive.  
Like #2 just assumed we would have more drivers over time.  there should probably be some mechanism, to allow modules with no package to be db drivers, maybe a `db.default_driver_package` which could be set to "" 

#3 this could easily be solved by having a config param in `db.driver_config`  which should probably just be the config, no need to have seperate sections since the db component only ever has a single db driver.  

As always we do accept pull requests
